<?php

/*
Plugin Name: On Tap
Plugin URI: http://www.bittersistersbrewery.com
Description: This plugin will be used to store and display all locations that Bitter Sisters is currently on tap at
Version: 1.0.0
Author: Tyler Walker
Author URI: http://www.chadtylerwalker.com
License: GPL2
*/

//global values for both version of plugin and version of DB
global $ontapVersion;
$ontapVersion = '1.0.0';
global $ontap_dontap_version;
$ontap_dontap_version = '1.0.0';

//This action will add in the correct scripts for using front-end
function ontap_scripts() {
    $googleAPIKey = 'AIzaSyDgVSO78uZ6ofVd2TzdYGwWxw-UcqsL7ck';

    //wp_register_script('google-maps-api', 'https://maps.googleapis.com/maps/api/js?key=' . $googleAPIKey, array(), '1.0.0', true);
    //wp_register_script('ontap-admin-form-handle',plugin_dir_url(__FILE__).'assets/js/ontap-form-handle.js', array(), '1.0.0', true);

} //end drag_drop_scripts()
add_action('wp_enqueue_scripts','ontap_scripts');



//This function will add scripts and css for the admin pages
function ontap_admin_scripts($hook) {
    wp_enqueue_style( 'ot-admin-styles', plugin_dir_url(__FILE__).'assets/dist/css/ontap.css');
}
add_action('admin_enqueue_scripts','ontap_admin_scripts');



//This action will add a menu page for the plugins options
function ontapAdmin() {
    //create menu page that is generated by _admin.php
    add_menu_page('On Tap','On Tap','manage_options','ontap/on-tap.php','','dashicons-exerpt-view',33);
    add_submenu_page('ontap/ontap.php','ontap/ontap.php','manage_options','ontap/on-tap-admin.php');
}
add_action('admin_menu','ontapAdmin');


//Create tables IMPORTANT
function ontap_dontap_install () {
    global $wpdb;
    global $ontap_dontap_version;

    //set variables for each table we want to create
    $table_name = $wpdb->prefix . "on_tap_locations";

    //find the charset for the DB. Could be changed depending on user
    $charset_collate = $wpdb->get_charset_collate();

    //add _table if dp_table does not already exist
    if($wpdb->get_var("SHOW TABLES LIKE '$table_name'") !== $table_name) {
        $sql = "CREATE TABLE $table_name (
            id mediumint(9) NOT NULL AUTO_INCREMENT PRIMARY KEY,
            location_name varchar(200) NULL,
            location_address1 varchar(250) NULL,
            location_address2 varchar(250) NULL,
            location_city varchar(150) NULL,
            location_state varchar(150) NULL,
            location_zip varchar(5) NULL,
            location_lat varchar(100) NULL,
            location_lng varchar(100) NULL,
            on_tap int(1) NOT NULL DEFAULT 1,
            deleted int(1) NOT NULL DEFAULT 1,
            UNIQUE KEY id (id)
            ) $charset_collate;";


        require_once(ABSPATH . 'wp-admin/includes/upgrade.php');
        dbDelta($sql);

        add_option('dp_data_version', $ontap_dontap_version);

    }

}// end ontap_dontap_install()
//register the DB table hook
register_activation_hook(__FILE__,'ontap_data_install');


// This function will add a shortcode
function ontap_shortcode($atts) {

    global $wpdb;

    $table_name = $wpdb->prefix.'on_tap';



    ?>

    <?php
}// end ontap_shortcode
add_shortcode('ontap','ontap_shortcode');